name: RPGPlugin
version: 1.1.1
main: com.zabrek.rpgplugin.infraestructure.RPGPlugin
description: RPG plugin for Paper
author: ZabrekMC
website: https://papermc.io
api-version: '26.2'

settings:
  attribute:
    maxDamage:
      max: 2048.0

libraries:
  - com.zaxxer:HikariCP:7.1.0

permissions:
  rpgplugin.player:
    description: Basic Permissions for Any RPG Player
    default: true
    children:
      rpgplugin.skills: true
      rpgplugin.use: true

commands:
  skills:
    description: Open the skill selection menu.
    usage: /skills
    permission: rpgplugin.skills
  use:
    description: It propels you through the air.
    usage: /use
    permission: rpgplugin.use